### PR TITLE
Allow text slides

### PR DESCRIPTION
**Pull request by FoamyGuy**
With these changes we can now use a file json file containing data like:
```json
{
  "text": "Sample Text\nSlideshow",
  "h_align": "CENTER",
  "v_align": "CENTER",
  "color": "0x0000FF",
  "background_color": "0xFF00FF",
  "scale": 2
}
```
It will create a label to show configured as specified by the json. `text` is the only required property. Any json files that do not contain `text` property are ignored. `h_align` and `v_align` properties from the json supersede the ones set on the SlideShow.

I have renamed many things that referred to "image" to now use "slide" instead since it can hold different types of things now. 

The sample json above is included in `examples/images/`

### CODE REVIEW

**Comment by FoamyGuy** [comment]
This probably closes #23 in my mind. This is a little more narrow than the issue mentions, but does fulfill the original goal of text and images mixed.

I have a few other things in mind I'd like to implement still:
- bitmap_font bdf file selected from the json data
- allow template variables to get filled in the text string

But I was interested to see if there is any feedback on the idea generally or what I have so far.

**Comment by ladyada** [comment]
@kattni please test

**Comment by kattni** [comment]
@FoamyGuy Hey! Thanks for adding this. I tried testing it on a PyBadge, and it's not working. I had to modify the simpletest to not have the `BACKLIGHT` line in it to make it work, and copied your example file to /, but it's still returning:
```
Traceback (most recent call last):
  File "code.py", line 12, in <module>
  File "/lib/adafruit_slideshow.py", line 271, in __init__
  File "/lib/adafruit_slideshow.py", line 439, in advance
RuntimeError: No valid images or text json files
```
My example code is:
```
import board
from adafruit_slideshow import PlayBackOrder, SlideShow

# pylint: disable=no-member

# Create the slideshow object that plays through once alphabetically.
slideshow = SlideShow(
    board.DISPLAY,
    folder="/",
    loop=False,
    order=PlayBackOrder.ALPHABETICAL,
)

while slideshow.update():
    pass
```
My CIRCUITPY drive:
Screen Shot 2020-11-18 at 15 17 35

**Comment by kattni** [comment]
I was informed that it requires `adafruit_display_text`. There was no indicator of this in the above error - probably worth making it more obvious. I added that library and am now getting a new error.
```
Traceback (most recent call last):
  File "code.py", line 11, in <module>
  File "/lib/adafruit_slideshow.py", line 237, in __init__
  File "/lib/adafruit_slideshow.py", line 239, in <listcomp>
  File "/lib/adafruit_slideshow.py", line 205, in _check_json_file
OSError: [Errno 2] No such file/directory: '//.fseventsd'
```

**Comment by FoamyGuy** [comment]
I think there may be some issue with the way it's trying to ignore hidden files whose name start with a dot. 

I will be working on this some more later tonight. I should be able to resolve the above error. I will also test it out on some MagTag, PyBadge as well and make any tweaks needed to get it working, so far all of my testing was on PyPortal.

I'm also hoping I can get the last two features mentioned implemented tonight, but unsure if I'll make it. I will make a comment here with the new status after my commits tonight.

**Comment by FoamyGuy** [comment]
The latest commits fix contain the following:
- correctly ignore hidden files
- correctly ignore non-json files
- removed an extra slash in the filepaths
- make the simpletest look in the images folder
- change the example text color to black and white for MagTag
- add warning to code and printout about optional support for text slides with `adafruit_display_text` requirement
- longer dwell time in the simpletest, better for MagTag

I tested this version successfully on PyBadge and MagTag. Here is how the example text json looks on the MagTag

image

**Comment by FoamyGuy** [comment]
The new commit adds support for custom fonts by declaring them in the json file like this one: 
```json
{
  "text": "Sample Text\nSlideshow",
  "h_align": "CENTER",
  "v_align": "CENTER",
  "color": "0x000000",
  "background_color": "0xFFFFFF",
  "scale": 2,
  "font": "Helvetica-Bold-16.bdf"
}
```
custom_font_slideshow


I did look into adding template variables but I think it's maybe something for the future. It needs some thought about how to pass the variables to the slideshow object.

I think this is ready to go now. 

One thing to note for @kattni  or whoever tests is the simpletest example is now looking in `/images/` instead of the root `/`. Paste the text json and any images you want to use into `/images/` on the device.

**Comment by FoamyGuy** [comment]
The new commit tweaks the colors to make use of grayscale on the MagTag.
image

**Review by kattni — APPROVED** [review]
Tested successfully on MagTag. Thanks for adding this feature!

**Pull request merged**
